#!/usr/bin/env bash

alias nf='neofetch --cpu_temp'
alias ls='lsd --color auto --icon always'
alias grep='grep --color=auto'
alias lsh='ls -lF --total-size'
alias lah='ls -alF --total-size'
alias ll='ls -lF'
alias la='ls -alF --git'
alias vim='nvim'
alias vimdiff='nvim -d'
alias gc='git clone'
alias findp='sudo pacman -Ss'
alias updt='sudo pacman -Syu'
alias orphan='sudo pacman -Qtdi'
alias orphsh="sudo pacman -Qtdi | grep -E '(Name|Description|Installed Size)'"
alias rmvp='sudo pacman -Rns'
alias ..='cd ..'
alias cd..='cd ..'
alias py='python3'
alias rm='rm -i'
alias df='df -kTh'
alias ok='okular'
alias mk='make'
alias mc='make clean'
alias sshroot='ssh root@matrix.linm-m.com'
alias sshuser='ssh venni@matrix.linm-m.com'
alias myvpn='sslocal -s linm-m.com -p 8388 -k sstaMAXiR! -m aes-256-gcm -l 1080'
