#!/usr/bin/env bash

alias nf='fastfetch'
alias btw='fastfetch'
alias ls='lsd --color auto --icon always'
alias grep='grep --color=auto'
alias lsh='ls -lF --total-size'
alias lah='ls -alF --total-size'
alias ll='ls -lF'
alias l='ls -lF'
alias la='ls -alF --git'
alias vim='nvim'
alias vi='vim'
alias vimdiff='nvim -d'
alias svim='sudo nvim'
alias gc='git clone'
alias gb='git branch'
alias gch='git checkout'
alias gadd='git add . && git diff --cached --stat'
alias gcached='git diff --cached'
alias orphan='sudo pacman -Qtdi'
alias orphsh="sudo pacman -Qtdi | grep -E '(Name|Description|Installed Size)'"
alias rmvp='sudo pacman -Rns'
alias ..='cd ..'
alias cd..='cd ..'
alias py='python3'
alias rm='rm -i'
alias df='df -kTh'
alias ok='okular'
alias mk='make'
alias mc='make clean'
alias sctl='sudo systemctl'
alias src='source ~/.bashrc'

# Maven
alias mrun='./mvnw spring-boot:run'
